controller_list:
  - name: fake_right_arm_controller
    joints:
      - r_shoulder_y
      - r_shoulder_x
      - r_arm_z
      - r_elbow_y
  - name: fake_left_arm_controller
    joints:
      - l_shoulder_y
      - l_shoulder_x
      - l_arm_z
      - l_elbow_y
  - name: fake_left_leg_controller
    joints:
      - l_hip_x
      - l_hip_z
      - l_hip_y
      - l_knee_y
      - l_ankle_y
  - name: fake_right_leg_controller
    joints:
      - l_hip_x
      - l_hip_z
      - l_hip_y
      - l_knee_y
      - l_ankle_y
  - name: fake_chest_controller
    joints:
      - abs_y
      - abs_x
      - abs_z
      - bust_y
      - bust_x